name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # Step 1 - Checks-out your repository under $GITHUB_WORKSPACE
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
    
    # Step 2 - Sets up the latest version of Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

    # Step 3 - Clean and don't fail
      - name: Clean public directory
        run: rm -rf public
    
    # Also specifies the theme we want to use
      - name: Build
        run: hugo --theme=fresh

      # - name: Build
      #   run: hugo --minify

    # Step 5 - Create name file
      - name: Create cname file
        run: echo 'freshswift.net' > public/CNAME

    # Step 6 - Push our generated site to our gh-pages branch
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.token_github }}
          publish_dir: ./public
